"""
PLMKR Fund-Phantom — structured grant data (Jade's real knowledge base).

Unit 1b (data-only): the real grant map, encoded as structured records, replacing
the old hand-invented mock list that lived inline in ``fund_phantom_service.py``.
Source of truth: JADE_GRANT_MAP_v2.md (Canada deep; US, UK, Australia, Germany,
France, the Nordics; crowdfunding as a situational category).

WHAT THIS MODULE IS (and is NOT):
  - DATA ONLY. No functions, no filtering logic, no I/O, no network, no secrets.
    ``fund_phantom_service`` imports GRANT_PROGRAMS and does all the searching /
    screening. The real-axis tool logic (country-aware search, project_type-in-
    ``funds``, currency-aware amounts) lands in Unit 2 — NOT here.
  - Every record is a plain, JSON-serializable dict so ``dict(p)`` in the service
    flows all fields (including the new ones) through untouched.

HARD RULES honored here:
  - NEVER invent an amount. If the map gives no real ballpark for a fund,
    ``amount_min`` / ``amount_max`` are None (not a guess), ``max_award`` is 0,
    and ``amount_notes`` says it's unlisted / verify live.
  - ``amount_is_approximate`` is True on EVERY record — per the map's own note that
    amounts shift yearly and must be verified live.
  - Deadlines are NOT stored (the map fetches them live). ``deadline_window`` holds
    only stable intake *cadence* (rolling / quarterly / annual / monthly /
    multiple / varies), never a specific date.
  - The open-ended structural tail is NOT enumerated as fake records: all 50 US
    state councils (incl. the illustrative NYSCA / California / Ohio), US city/
    county agencies, the Australian state bodies (NSW/Vic/Qld/Tas/ACT/WA), Canadian
    municipal beyond Toronto, and UK local councils stay as category knowledge in
    the prose bank. Only funds the map actually names are encoded.

SCHEMA (per record):
  Identity / routing:
    id, name, funder, country, url
  Real classification axes (data now; Unit-2 logic will read these):
    track, scope, funds, residency, language
  Amounts (never invented):
    currency, amount_min, amount_max, amount_is_approximate, amount_notes
  Cadence (stable; specific dates are live-lookup):
    deadline_window
  Back-compat axes (KEPT lossy — the real-axis switch is Unit 2):
    genre, region, focus, max_award
  Detail level (Unit-1b addition):
    detail_level  ("full" | "stub")
"""

# ── Controlled vocabularies (reference constants — data only, no logic) ───────
# These pin the allowed values the Unit-1a schema specified. Nothing in this
# module enforces them; they exist so Unit 2 (and reviewers) have one place to
# read the vocab from.

TRACK = ("industry", "arts_council", "crowdfunding")

SCOPE = ("federal", "national", "provincial", "state", "municipal", "regional", "global")

# What a fund pays for. Tokens used across the records below.
FUNDS_VOCAB = frozenset({
    "recording", "touring", "video", "production", "creation", "composition",
    "development", "marketing", "promotion", "export", "showcase", "sync",
    "mentorship", "travel", "business", "infrastructure",
})

# Back-compat lossy axes (retained until Unit 2 switches to the real axes above).
REGION_BACKCOMPAT = ("national", "regional")


# ── Grant program library (structured from JADE_GRANT_MAP_v2.md) ──────────────
GRANT_PROGRAMS = [
    # ═══════════════════════ CANADA ═══════════════════════
    # ── Federal ──
    {
        "id": "factor-canada-music-fund",
        "name": "FACTOR (Canada Music Fund)",
        "funder": "FACTOR",
        "country": "CA",
        "url": "factor.ca",
        "track": "industry",
        "scope": "federal",
        "funds": ("recording", "touring", "video", "development", "marketing"),
        "residency": "English-language Canadian commercial artists + Canadian-controlled companies; rated FACTOR profile required",
        "language": "en",
        "currency": "CAD",
        "amount_min": 5000,
        "amount_max": 75000,
        "amount_is_approximate": True,
        "amount_notes": "Artist Development ~$5,000 (75% cost share); up to ~$67,500/album; ~$25,000 single/EP; up to ~$75,000 live performance. Multiple intake windows across the Apr–Mar fiscal year — verify live.",
        "deadline_window": "multiple",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 75000,
        "detail_level": "full",
    },
    {
        "id": "musicaction",
        "name": "Musicaction",
        "funder": "Musicaction",
        "country": "CA",
        "url": "musicaction.ca",
        "track": "industry",
        "scope": "federal",
        "funds": ("recording", "touring", "video", "development", "marketing"),
        "residency": "French-language Canadian artists/companies (Quebec French-language equivalent of FACTOR)",
        "language": "fr",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Per-scheme amounts not listed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "canada-council-arts",
        "name": "Canada Council for the Arts",
        "funder": "Canada Council for the Arts",
        "country": "CA",
        "url": "canadacouncil.ca",
        "track": "arts_council",
        "scope": "federal",
        "funds": ("creation", "touring", "development"),
        "residency": "Canadian citizens / permanent residents; judged on artistic merit",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": 200000,
        "amount_is_approximate": True,
        "amount_notes": "Explore & Create up to ~$75,000; Circulation & Touring up to ~$200,000 (50% budget); Arts Abroad up to ~$30,000 — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 200000,
        "detail_level": "full",
    },
    {
        "id": "socan-foundation",
        "name": "SOCAN Foundation",
        "funder": "SOCAN Foundation",
        "country": "CA",
        "url": "socanfoundation.ca",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "composition", "development"),
        "residency": "Canadian music creators; some streams orgs/students only",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": 10000,
        "amount_is_approximate": True,
        "amount_notes": "Music Creator Day Grants up to $10,000 (orgs); Work Commissioning Assistance; Music Creator Scholarship (students) — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 10000,
        "detail_level": "full",
    },
    {
        "id": "creative-export-canada",
        "name": "Creative Export Canada",
        "funder": "Canadian Heritage",
        "country": "CA",
        "url": "",
        "track": "industry",
        "scope": "federal",
        "funds": ("export", "business", "development"),
        "residency": "Canadian music businesses expanding internationally",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "International expansion for music businesses; amounts not listed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    # ── Provincial ──
    {
        "id": "ontario-creates-omif",
        "name": "Ontario Music Investment Fund (OMIF)",
        "funder": "Ontario Creates",
        "country": "CA",
        "url": "ontariocreates.ca",
        "track": "industry",
        "scope": "provincial",
        "funds": ("recording", "marketing", "development"),
        "residency": "Ontario labels/publishers + high-potential self-releasing BIPOC/Francophone artist-entrepreneurs; min $25k revenue",
        "language": "",
        "currency": "CAD",
        "amount_min": 10000,
        "amount_max": 200000,
        "amount_is_approximate": True,
        "amount_notes": "Music Creation stream: up to 50% costs, cap $200k, min request $10k; min $25k revenue eligibility. Two intake rounds/year — verify live.",
        "deadline_window": "multiple",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 200000,
        "detail_level": "full",
    },
    {
        "id": "ontario-arts-council",
        "name": "Ontario Arts Council",
        "funder": "Ontario Arts Council",
        "country": "CA",
        "url": "arts.on.ca",
        "track": "arts_council",
        "scope": "provincial",
        "funds": ("recording", "production", "creation"),
        "residency": "Ontario-based artists",
        "language": "",
        "currency": "CAD",
        "amount_min": 5000,
        "amount_max": 20000,
        "amount_is_approximate": True,
        "amount_notes": "Music Production & Presentation $5k–$20k; Music Recording up to $10k; Music Creation Projects (all stages) — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 20000,
        "detail_level": "full",
    },
    {
        "id": "amplify-bc",
        "name": "Amplify BC",
        "funder": "Creative BC",
        "country": "CA",
        "url": "amplifybc.ca",
        "track": "industry",
        "scope": "provincial",
        "funds": ("business", "development", "recording", "marketing"),
        "residency": "BC artists, presenters, companies",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": 10000,
        "amount_is_approximate": True,
        "amount_notes": "Business Foundations up to $10k; multiple streams for BC artists/presenters/companies — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 10000,
        "detail_level": "full",
    },
    {
        "id": "calq-quebec",
        "name": "Conseil des arts et des lettres du Québec (CALQ)",
        "funder": "CALQ",
        "country": "CA",
        "url": "calq.gouv.qc.ca",
        "track": "arts_council",
        "scope": "provincial",
        "funds": ("creation", "production"),
        "residency": "Canadian citizen/PR resident of Québec 12+ months; up to 5 apps/grants per fiscal year; English projects eligible",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Creation/production grants; response ~4 months; apply ≥4 weeks ahead. Per-grant amounts not listed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "full",
    },
    {
        "id": "sodec-quebec",
        "name": "SODEC",
        "funder": "SODEC",
        "country": "CA",
        "url": "",
        "track": "industry",
        "scope": "provincial",
        "funds": ("business", "development"),
        "residency": "Québec cultural enterprises",
        "language": "fr",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Cultural-enterprise financing; amounts not listed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "saskmusic-creative-sask",
        "name": "Creative Saskatchewan / SaskMusic",
        "funder": "Creative Saskatchewan",
        "country": "CA",
        "url": "creativesask.ca",
        "track": "industry",
        "scope": "provincial",
        "funds": ("recording", "touring", "marketing", "showcase"),
        "residency": "Saskatchewan artists; Tour Support needs min 6 confirmed shows",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Sound Recording; Tour Support (min 6 shows); Marketing (Micro/Major); Showcase/Sell Travel. Amounts not listed in map — verify live.",
        "deadline_window": "multiple",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "full",
    },
    {
        "id": "manitoba-film-music",
        "name": "Manitoba Film & Music",
        "funder": "Manitoba Film & Music",
        "country": "CA",
        "url": "",
        "track": "industry",
        "scope": "provincial",
        "funds": ("recording", "marketing", "touring"),
        "residency": "Manitoba artists; Perform stream = touring outside hometown; out-of-province stream",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Produce (recording), Promote (marketing), Perform (touring). Amounts not listed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "alberta-music-afa",
        "name": "Alberta Music / Alberta Foundation for the Arts",
        "funder": "Alberta Foundation for the Arts",
        "country": "CA",
        "url": "",
        "track": "arts_council",
        "scope": "provincial",
        "funds": ("creation", "recording", "development"),
        "residency": "Alberta artists",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Primary provincial arts funder; specifics not detailed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    # ── Atlantic ──
    {
        "id": "arts-nova-scotia",
        "name": "Arts Nova Scotia",
        "funder": "Arts Nova Scotia",
        "country": "CA",
        "url": "artsns.ca",
        "track": "arts_council",
        "scope": "provincial",
        "funds": ("creation", "development"),
        "residency": "NS residents 12+ months; excludes commercial recording (routes to Music NS)",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": 15000,
        "amount_is_approximate": True,
        "amount_notes": "Create up to $15k; Present up to $5k; Professional Development up to $5k. Excludes commercial recording — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 15000,
        "detail_level": "full",
    },
    {
        "id": "music-nova-scotia",
        "name": "Music Nova Scotia",
        "funder": "Music Nova Scotia",
        "country": "CA",
        "url": "musicnovascotia.ca",
        "track": "industry",
        "scope": "provincial",
        "funds": ("marketing", "mentorship", "recording", "showcase", "touring", "creation", "sync"),
        "residency": "NS artists, tiered by stage (Artist I etc.)",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Tiered programs: Marketing, Mentorship, Recording, Showcase, Tour Support, Artistic Creation; Sync Nova Scotia = 25% licensing-fee subsidy for NS songs. Amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "full",
    },
    {
        "id": "music-nb",
        "name": "Music·Musique NB",
        "funder": "Music·Musique NB",
        "country": "CA",
        "url": "musicnb.org",
        "track": "industry",
        "scope": "provincial",
        "funds": ("development", "marketing", "recording"),
        "residency": "New Brunswick music industry",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Music Industry Development Program (MID). Amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "artsnb-new-brunswick",
        "name": "artsnb (New Brunswick Arts Board)",
        "funder": "artsnb",
        "country": "CA",
        "url": "artsnb.ca",
        "track": "arts_council",
        "scope": "provincial",
        "funds": ("development", "creation", "infrastructure", "travel"),
        "residency": "New Brunswick artists",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Career Development, Creation, Arts Infrastructure (equipment), Professional Project grants, Travel Fund. Amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "full",
    },
    {
        "id": "music-pei",
        "name": "Music PEI",
        "funder": "Music PEI",
        "country": "CA",
        "url": "musicpei.com",
        "track": "industry",
        "scope": "provincial",
        "funds": ("recording", "marketing", "touring", "business", "travel"),
        "residency": "PEI members only; stages Emerging / Export Ready / Career / Industry Pro",
        "language": "",
        "currency": "CAD",
        "amount_min": 500,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Investment Program by career stage (recording, marketing, tour, market access, business travel); Microgrants ~$500. Larger amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "full",
    },
    {
        "id": "musicnl",
        "name": "MusicNL",
        "funder": "MusicNL",
        "country": "CA",
        "url": "musicnl.ca",
        "track": "industry",
        "scope": "provincial",
        "funds": ("recording", "marketing", "development"),
        "residency": "Newfoundland & Labrador artists; local-spend rule (non-NL vendor 80%, top tier 100%); grant-writing consultant fees eligible up to 10% of request",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Artist Development (singles/EPs/albums + marketing, all genres). Amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "full",
    },
    {
        "id": "artsnl",
        "name": "ArtsNL",
        "funder": "ArtsNL",
        "country": "CA",
        "url": "",
        "track": "arts_council",
        "scope": "provincial",
        "funds": ("creation", "development"),
        "residency": "Newfoundland & Labrador artists",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Provincial arts council; specifics not detailed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    # ── Municipal ──
    {
        "id": "toronto-arts-council",
        "name": "Toronto Arts Council",
        "funder": "Toronto Arts Council",
        "country": "CA",
        "url": "torontoartscouncil.org",
        "track": "arts_council",
        "scope": "municipal",
        "funds": ("creation", "recording", "production"),
        "residency": "Toronto residents, citizens/PRs",
        "language": "",
        "currency": "CAD",
        "amount_min": None,
        "amount_max": 15000,
        "amount_is_approximate": True,
        "amount_notes": "Music Creation & Audio Recording; Music Projects (orgs/collectives) up to $15k at 50% budget; Accessibility Grant up to $5k — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 15000,
        "detail_level": "full",
    },

    # ═══════════════════════ UNITED STATES ═══════════════════════
    # No commercial-music industry funder; NEA does not fund individuals directly.
    # ── Federal ──
    {
        "id": "nea-grants-for-arts-projects",
        "name": "NEA — Grants for Arts Projects",
        "funder": "National Endowment for the Arts",
        "country": "US",
        "url": "arts.gov",
        "track": "arts_council",
        "scope": "federal",
        "funds": ("touring", "development", "production"),
        "residency": "US organizations only (individuals need a nonprofit fiscal sponsor); 1:1 match",
        "language": "",
        "currency": "USD",
        "amount_min": 10000,
        "amount_max": 100000,
        "amount_is_approximate": True,
        "amount_notes": "$10,000–$100,000, 1:1 match; music eligible (domestic touring, festivals, professional development; not international tours). Two cycles/year — verify live.",
        "deadline_window": "multiple",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 100000,
        "detail_level": "full",
    },
    {
        "id": "nea-challenge-america",
        "name": "NEA — Challenge America",
        "funder": "National Endowment for the Arts",
        "country": "US",
        "url": "arts.gov",
        "track": "arts_council",
        "scope": "federal",
        "funds": ("development", "production"),
        "residency": "Small US orgs reaching underserved communities",
        "language": "",
        "currency": "USD",
        "amount_min": 10000,
        "amount_max": 10000,
        "amount_is_approximate": True,
        "amount_notes": "$10,000 fixed grant for small orgs reaching underserved communities — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 10000,
        "detail_level": "full",
    },
    # ── National (private / nonprofit) ──
    {
        "id": "new-music-usa-creator-fund",
        "name": "New Music USA — Creator Fund",
        "funder": "New Music USA",
        "country": "US",
        "url": "newmusicusa.org",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "composition", "development"),
        "residency": "US individuals, any genre; runs on regional cycles (check which region is open)",
        "language": "",
        "currency": "USD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "New-work creation, collaboration, childcare, skills-building; regional cycles. Amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "full",
    },
    {
        "id": "new-music-usa-organization-fund",
        "name": "New Music USA — Organization Fund",
        "funder": "New Music USA",
        "country": "US",
        "url": "newmusicusa.org",
        "track": "arts_council",
        "scope": "national",
        "funds": ("development", "production"),
        "residency": "US orgs only",
        "language": "",
        "currency": "USD",
        "amount_min": None,
        "amount_max": 10000,
        "amount_is_approximate": True,
        "amount_notes": "Orgs only; average ~$7,000, max $10,000 — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 10000,
        "detail_level": "full",
    },

    # ═══════════════════════ UNITED KINGDOM ═══════════════════════
    # ── UK-wide (industry / charitable) ──
    {
        "id": "prs-open-fund",
        "name": "PRS Foundation — Open Fund for Music Creators",
        "funder": "PRS Foundation",
        "country": "UK",
        "url": "prsfoundation.com",
        "track": "industry",
        "scope": "national",
        "funds": ("creation", "touring", "promotion"),
        "residency": "UK individuals, any genre",
        "language": "",
        "currency": "GBP",
        "amount_min": None,
        "amount_max": 5000,
        "amount_is_approximate": True,
        "amount_notes": "Up to £5,000; creation + performance + promotion of new music — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 5000,
        "detail_level": "full",
    },
    {
        "id": "ppl-momentum-music-fund",
        "name": "PPL Momentum Music Fund",
        "funder": "PPL / PRS Foundation",
        "country": "UK",
        "url": "prsfoundation.com",
        "track": "industry",
        "scope": "national",
        "funds": ("recording", "touring", "marketing"),
        "residency": "UK artists at breakthrough stage",
        "language": "",
        "currency": "GBP",
        "amount_min": 5000,
        "amount_max": 15000,
        "amount_is_approximate": True,
        "amount_notes": "£5k–£15k; recording, touring, marketing — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 15000,
        "detail_level": "full",
    },
    {
        "id": "prs-international-showcase-fund",
        "name": "PRS Foundation — International Showcase Fund (ISF)",
        "funder": "PRS Foundation",
        "country": "UK",
        "url": "prsfoundation.com",
        "track": "industry",
        "scope": "national",
        "funds": ("showcase", "travel", "export"),
        "residency": "UK artists formally invited to international industry showcases/conferences",
        "language": "",
        "currency": "GBP",
        "amount_min": None,
        "amount_max": 5500,
        "amount_is_approximate": True,
        "amount_notes": "Up to £5,500 for UK artists invited to international showcases — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 5500,
        "detail_level": "full",
    },
    {
        "id": "prs-women-make-music",
        "name": "PRS Foundation — Women Make Music",
        "funder": "PRS Foundation",
        "country": "UK",
        "url": "prsfoundation.com",
        "track": "industry",
        "scope": "national",
        "funds": ("creation", "development"),
        "residency": "UK women / gender-expansive music creators",
        "language": "",
        "currency": "GBP",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Amounts not listed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "prs-power-up",
        "name": "PRS Foundation — POWER UP",
        "funder": "PRS Foundation",
        "country": "UK",
        "url": "prsfoundation.com",
        "track": "industry",
        "scope": "national",
        "funds": ("development", "creation"),
        "residency": "Black music creators and industry professionals in the UK",
        "language": "",
        "currency": "GBP",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Amounts not listed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "prs-early-career-promoter-fund",
        "name": "PRS Foundation — Early Career Promoter Fund",
        "funder": "PRS Foundation",
        "country": "UK",
        "url": "prsfoundation.com",
        "track": "industry",
        "scope": "national",
        "funds": ("promotion", "development"),
        "residency": "Early-career promoters in England",
        "language": "",
        "currency": "GBP",
        "amount_min": None,
        "amount_max": 3500,
        "amount_is_approximate": True,
        "amount_notes": "Up to £3,500 for England promoters — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 3500,
        "detail_level": "full",
    },
    {
        "id": "help-musicians",
        "name": "Help Musicians",
        "funder": "Help Musicians UK",
        "country": "UK",
        "url": "helpmusicians.org.uk",
        "track": "industry",
        "scope": "national",
        "funds": ("development", "recording"),
        "residency": "UK musicians",
        "language": "",
        "currency": "GBP",
        "amount_min": 500,
        "amount_max": 3000,
        "amount_is_approximate": True,
        "amount_notes": "Fast Track up to £500 (short-notice); Next Level Award up to £3,000 + development — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 3000,
        "detail_level": "full",
    },
    {
        "id": "youth-music-nextgen",
        "name": "Youth Music NextGen Fund",
        "funder": "Youth Music",
        "country": "UK",
        "url": "",
        "track": "industry",
        "scope": "national",
        "funds": ("development", "creation"),
        "residency": "UK under-25s / early career",
        "language": "",
        "currency": "GBP",
        "amount_min": None,
        "amount_max": 3000,
        "amount_is_approximate": True,
        "amount_notes": "Up to £3,000 for under-25s / early career — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 3000,
        "detail_level": "full",
    },
    # ── National arts councils ──
    {
        "id": "arts-council-england",
        "name": "Arts Council England — National Lottery Project Grants",
        "funder": "Arts Council England",
        "country": "UK",
        "url": "artscouncil.org.uk",
        "track": "arts_council",
        "scope": "national",
        "funds": ("recording", "touring", "video", "development"),
        "residency": "England-based individuals + orgs",
        "language": "",
        "currency": "GBP",
        "amount_min": 1000,
        "amount_max": 100000,
        "amount_is_approximate": True,
        "amount_notes": "£1,000–£100,000; releases, tours, visuals, talent development; rolling. Plus Supporting Grassroots Music — verify live.",
        "deadline_window": "rolling",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 100000,
        "detail_level": "full",
    },
    {
        "id": "creative-scotland",
        "name": "Creative Scotland",
        "funder": "Creative Scotland",
        "country": "UK",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "development"),
        "residency": "Scotland-based artists",
        "language": "",
        "currency": "GBP",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Devolved arts council; amounts not detailed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "arts-council-wales",
        "name": "Arts Council of Wales",
        "funder": "Arts Council of Wales",
        "country": "UK",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "development"),
        "residency": "Wales-based artists",
        "language": "",
        "currency": "GBP",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Devolved arts council; amounts not detailed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "arts-council-northern-ireland",
        "name": "Arts Council of Northern Ireland",
        "funder": "Arts Council of Northern Ireland",
        "country": "UK",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "development"),
        "residency": "Northern Ireland-based artists",
        "language": "",
        "currency": "GBP",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Devolved arts council; amounts not detailed in map — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },

    # ═══════════════════════ AUSTRALIA ═══════════════════════
    # ── Federal — Creative Australia / Music Australia ──
    {
        "id": "music-australia-export-development-fund",
        "name": "Music Australia — Export Development Fund",
        "funder": "Creative Australia / Music Australia",
        "country": "AU",
        "url": "creative.gov.au",
        "track": "industry",
        "scope": "federal",
        "funds": ("touring", "showcase", "export", "development"),
        "residency": "Australian citizens/PRs; 50% matched funding required (no in-kind, no other govt grants as match)",
        "language": "",
        "currency": "AUD",
        "amount_min": 3000,
        "amount_max": 75000,
        "amount_is_approximate": True,
        "amount_notes": "Cat 1 (int'l performance/touring) up to $75,000; Cat 2 (professional/artistic dev) $3,000–$15,000; quarterly rounds — verify live.",
        "deadline_window": "quarterly",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 75000,
        "detail_level": "full",
    },
    {
        "id": "music-australia-label-marketing-manufacturing",
        "name": "Music Australia — Record Label Marketing & Manufacturing Grants",
        "funder": "Creative Australia / Music Australia",
        "country": "AU",
        "url": "creative.gov.au",
        "track": "industry",
        "scope": "federal",
        "funds": ("marketing", "production", "business"),
        "residency": "Australian-owned labels/services/distributors with 2+ active artists",
        "language": "",
        "currency": "AUD",
        "amount_min": None,
        "amount_max": 10000,
        "amount_is_approximate": True,
        "amount_notes": "Up to $10,000 matched — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 10000,
        "detail_level": "full",
    },
    {
        "id": "music-australia-core-contribution-fund",
        "name": "Music Australia — Core Contribution Fund",
        "funder": "Creative Australia / Music Australia",
        "country": "AU",
        "url": "creative.gov.au",
        "track": "industry",
        "scope": "federal",
        "funds": ("business", "development"),
        "residency": "Peak bodies / member orgs; 2-year core funding",
        "language": "",
        "currency": "AUD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "2-year core funding for peak bodies; amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "creative-australia-arts-projects",
        "name": "Creative Australia — Arts Projects for Individuals & Groups",
        "funder": "Creative Australia",
        "country": "AU",
        "url": "creative.gov.au",
        "track": "arts_council",
        "scope": "federal",
        "funds": ("creation", "production", "development"),
        "residency": "Australian artists; contemporary music assessed by a separate peer panel",
        "language": "",
        "currency": "AUD",
        "amount_min": 10000,
        "amount_max": 50000,
        "amount_is_approximate": True,
        "amount_notes": "$10,000–$50,000 — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 50000,
        "detail_level": "full",
    },
    # ── State / export ──
    {
        "id": "createsa-music-development-office",
        "name": "CreateSA — Music Development Office",
        "funder": "CreateSA (South Australia)",
        "country": "AU",
        "url": "",
        "track": "industry",
        "scope": "state",
        "funds": ("creation", "business", "development"),
        "residency": "South Australia artists; Stream A creative / Stream B business",
        "language": "",
        "currency": "AUD",
        "amount_min": None,
        "amount_max": 15000,
        "amount_is_approximate": True,
        "amount_notes": "Project Support Grants up to $15,000 (Stream A creative / Stream B business) — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 15000,
        "detail_level": "full",
    },
    {
        "id": "sounds-australia",
        "name": "Sounds Australia",
        "funder": "Sounds Australia",
        "country": "AU",
        "url": "soundsaustralia.com.au",
        "track": "industry",
        "scope": "national",
        "funds": ("showcase", "travel", "export"),
        "residency": "Australian artists with official showcase invitations (SXSW, Great Escape, Reeperbahn, etc.)",
        "language": "",
        "currency": "AUD",
        "amount_min": None,
        "amount_max": 3000,
        "amount_is_approximate": True,
        "amount_notes": "Export facilitation; state export contribution funds ~$3,000 travel top-ups for official showcase invitations — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 3000,
        "detail_level": "full",
    },

    # ═══════════════════════ GERMANY ═══════════════════════
    # Applications must be in German.
    {
        "id": "initiative-musik-artist-funding",
        "name": "Initiative Musik — Artist Funding",
        "funder": "Initiative Musik",
        "country": "DE",
        "url": "initiative-musik.de",
        "track": "industry",
        "scope": "national",
        "funds": ("composition", "production", "recording", "video", "promotion", "touring"),
        "residency": "German solo artists/bands (popular music), often with an industry partner; 'up-and-coming' criteria; German-language applications only",
        "language": "de",
        "currency": "EUR",
        "amount_min": 6000,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Degressive grant (at €10,000 total spend up to 60% funded; min 40% own contribution); min request €6,000 (min €10,000 total project). No stated award ceiling. German-language only — verify live.",
        "deadline_window": "monthly",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "full",
    },
    {
        "id": "initiative-musik-export-funding",
        "name": "Initiative Musik — Export Funding",
        "funder": "Initiative Musik",
        "country": "DE",
        "url": "initiative-musik.de",
        "track": "industry",
        "scope": "national",
        "funds": ("touring", "showcase", "export", "marketing"),
        "residency": "German artists/SMEs; International Live & Showcase (up to 15 performances abroad) + GO! Export",
        "language": "de",
        "currency": "EUR",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "International Live & Showcase (travel + marketing, up to 15 shows abroad); GO! Export (industry SMEs). Amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "full",
    },
    {
        "id": "musicboard-berlin",
        "name": "Musicboard Berlin",
        "funder": "Musicboard Berlin",
        "country": "DE",
        "url": "",
        "track": "industry",
        "scope": "municipal",
        "funds": ("creation", "development", "touring"),
        "residency": "Berlin-based popular-music artists",
        "language": "de",
        "currency": "EUR",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Berlin regional music funding; amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "hamburg-label-funding",
        "name": "Hamburg Label Funding",
        "funder": "City of Hamburg",
        "country": "DE",
        "url": "",
        "track": "industry",
        "scope": "municipal",
        "funds": ("business", "recording", "marketing"),
        "residency": "Hamburg-based labels",
        "language": "de",
        "currency": "EUR",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Hamburg regional label funding; amounts not listed — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },

    # ═══════════════════════ FRANCE ═══════════════════════
    # Mostly French-language.
    {
        "id": "cnm-france",
        "name": "Centre national de la musique (CNM)",
        "funder": "Centre national de la musique",
        "country": "FR",
        "url": "cnm.fr",
        "track": "industry",
        "scope": "national",
        "funds": ("creation", "production", "touring", "export"),
        "residency": "France-based artists, songwriters, labels, publishers, managers, promoters, venues, festivals; mostly French-language",
        "language": "fr",
        "currency": "EUR",
        "amount_min": None,
        "amount_max": 200000,
        "amount_is_approximate": True,
        "amount_notes": "Schemes for creation, production, touring, export. International development: same project max 3 grants/yr; cap €200,000/yr per beneficiary org across international programs (an aggregate cap, not a single award) — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 200000,
        "detail_level": "full",
    },
    {
        "id": "drac-france",
        "name": "DRAC / Regional Councils (France)",
        "funder": "DRAC (regional cultural affairs)",
        "country": "FR",
        "url": "",
        "track": "arts_council",
        "scope": "regional",
        "funds": ("creation", "production"),
        "residency": "France, region-specific; mostly French-language",
        "language": "fr",
        "currency": "EUR",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Regional cultural-affairs (DRAC) + regional council music/creation funds; amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "regional",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },

    # ═══════════════════════ THE NORDICS ═══════════════════════
    # Each country pairs a music export office with an arts council.
    # Per-scheme amounts vary — verify live (all None here, per the map).
    {
        "id": "export-music-sweden",
        "name": "Export Music Sweden (ExMS)",
        "funder": "Export Music Sweden",
        "country": "SE",
        "url": "exms.org",
        "track": "industry",
        "scope": "national",
        "funds": ("export", "showcase", "travel"),
        "residency": "Swedish music industry (export)",
        "language": "",
        "currency": "SEK",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Industry export office; per-scheme amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "kulturradet-sweden",
        "name": "Kulturrådet (Swedish Arts Council)",
        "funder": "Kulturrådet",
        "country": "SE",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "production"),
        "residency": "Sweden-based artists",
        "language": "",
        "currency": "SEK",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Arts council creation funding; amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "konstnarsnamnden-sweden",
        "name": "Konstnärsnämnden (Swedish Arts Grants Committee)",
        "funder": "Konstnärsnämnden",
        "country": "SE",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "development"),
        "residency": "Sweden-based artists; creation/working grants",
        "language": "",
        "currency": "SEK",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Working/creation grants; amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "music-norway",
        "name": "Music Norway",
        "funder": "Music Norway",
        "country": "NO",
        "url": "musicnorway.no",
        "track": "industry",
        "scope": "national",
        "funds": ("export", "showcase", "travel"),
        "residency": "Norwegian music industry (export; administers travel/export schemes for the Foreign Ministry)",
        "language": "",
        "currency": "NOK",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Export office administering travel/export schemes; amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "arts-council-norway",
        "name": "Kulturrådet / Arts Council Norway",
        "funder": "Arts Council Norway",
        "country": "NO",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "production"),
        "residency": "Norway-based artists",
        "language": "",
        "currency": "NOK",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Arts council creation funding; amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "fond-utovende-kunstnere-norway",
        "name": "Fond for utøvende kunstnere (FFUK)",
        "funder": "Fond for utøvende kunstnere",
        "country": "NO",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "development"),
        "residency": "Norway-based performing artists",
        "language": "",
        "currency": "NOK",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Fund for performing artists; amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "music-export-denmark",
        "name": "Music Export Denmark (MXD)",
        "funder": "Music Export Denmark",
        "country": "DK",
        "url": "",
        "track": "industry",
        "scope": "national",
        "funds": ("export", "showcase", "travel"),
        "residency": "Danish music industry (export)",
        "language": "",
        "currency": "DKK",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Export office; per-scheme amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "danish-arts-foundation",
        "name": "Danish Arts Foundation (Statens Kunstfond)",
        "funder": "Statens Kunstfond",
        "country": "DK",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "production"),
        "residency": "Denmark-based artists",
        "language": "",
        "currency": "DKK",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Arts foundation creation funding; amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "koda-kultur-denmark",
        "name": "Koda Kultur",
        "funder": "Koda",
        "country": "DK",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "composition"),
        "residency": "Danish songwriters/composers",
        "language": "",
        "currency": "DKK",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Cultural funding for composers/songwriters; amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "music-finland-mes",
        "name": "Music Finland / MES",
        "funder": "Music Finland",
        "country": "FI",
        "url": "",
        "track": "industry",
        "scope": "national",
        "funds": ("export", "showcase", "recording"),
        "residency": "Finnish music industry (export)",
        "language": "",
        "currency": "EUR",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Export office; per-scheme amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "taike-finland",
        "name": "Taike (Arts Promotion Centre Finland)",
        "funder": "Taike",
        "country": "FI",
        "url": "",
        "track": "arts_council",
        "scope": "national",
        "funds": ("creation", "production"),
        "residency": "Finland-based artists",
        "language": "",
        "currency": "EUR",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Arts promotion centre (production/creation); amounts vary — verify live.",
        "deadline_window": "varies",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },

    # ═══════════════════════ CROWDFUNDING ═══════════════════════
    # Situational / secondary option — fan-raised campaign money, NOT
    # apply-and-qualify grant money. track="crowdfunding". Amounts always depend
    # on the campaign, so never a fixed ballpark here.
    {
        "id": "kickstarter",
        "name": "Kickstarter",
        "funder": "Kickstarter",
        "country": "",
        "url": "kickstarter.com",
        "track": "crowdfunding",
        "scope": "global",
        "funds": ("recording", "production", "creation"),
        "residency": "Open (platform); supported countries only",
        "language": "",
        "currency": "",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "All-or-nothing project funding (hit target or nothing charged); strong for defined releases/vinyl runs. Amount depends on the campaign — verify live.",
        "deadline_window": "rolling",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "indiegogo",
        "name": "Indiegogo",
        "funder": "Indiegogo",
        "country": "",
        "url": "indiegogo.com",
        "track": "crowdfunding",
        "scope": "global",
        "funds": ("recording", "production", "creation"),
        "residency": "Open (platform); supported countries only",
        "language": "",
        "currency": "",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Flexible or fixed funding; keeps what you raise. Amount depends on the campaign — verify live.",
        "deadline_window": "rolling",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "patreon",
        "name": "Patreon",
        "funder": "Patreon",
        "country": "",
        "url": "patreon.com",
        "track": "crowdfunding",
        "scope": "global",
        "funds": ("development",),
        "residency": "Open (platform); supported countries only",
        "language": "",
        "currency": "",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Ongoing fan subscriptions (recurring income, not a one-off project). Amount depends on the fan base — verify live.",
        "deadline_window": "rolling",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "bandcamp",
        "name": "Bandcamp",
        "funder": "Bandcamp",
        "country": "",
        "url": "bandcamp.com",
        "track": "crowdfunding",
        "scope": "global",
        "funds": ("recording", "development"),
        "residency": "Open (platform)",
        "language": "",
        "currency": "",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Music-native; direct sales + fan support + subscriptions. Amount depends on sales/fans — verify live.",
        "deadline_window": "rolling",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "gofundme",
        "name": "GoFundMe",
        "funder": "GoFundMe",
        "country": "",
        "url": "gofundme.com",
        "track": "crowdfunding",
        "scope": "global",
        "funds": ("development",),
        "residency": "Open (platform); supported countries only",
        "language": "",
        "currency": "",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Informal, no music-native tooling; lower-friction for personal/emergency asks. Amount depends on the campaign — verify live.",
        "deadline_window": "rolling",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
    {
        "id": "australian-cultural-fund",
        "name": "Australian Cultural Fund",
        "funder": "Creative Partnerships Australia",
        "country": "AU",
        "url": "australianculturalfund.org.au",
        "track": "crowdfunding",
        "scope": "national",
        "funds": ("recording", "production", "creation"),
        "residency": "Australian artists; tax-deductible donations, matched by some grants",
        "language": "",
        "currency": "AUD",
        "amount_min": None,
        "amount_max": None,
        "amount_is_approximate": True,
        "amount_notes": "Tax-deductible donation platform; income can count toward Creative Australia matched-funding requirements. Amount depends on the campaign — verify live.",
        "deadline_window": "rolling",
        "genre": "any",
        "region": "national",
        "focus": "any",
        "max_award": 0,
        "detail_level": "stub",
    },
]
