"""
Phase 3e — Per-agent deep consult test for mech-ledger.

Scope: mech-ledger only. Home domain "finance_royalties". Six realistic
questions an artist or their team would ask Finn (Mechanical Royalties
Specialist), covering: MLC collection vs. co-write split sheet, label
contract dispute over mechanical clause, catalog-wide royalty tracking
aligned to distribution deal waterfall, streaming data income forecasting,
sync placement mechanical collection, and a deliberately narrow statutory
rate question.

For each cross-domain question we assert:
  (a) mech-ledger's home domain "finance_royalties" leads the result list.
  (b) Every expected cross-domain appears in the result.

One deliberately narrow question asserts home-only with no spurious
cross-domain — only "mechanical" and rate-adjacent terms trigger (CRB ruling /
MLC disbursements, no publishing, no legal, no sync, no analytics terms).

All tests are deterministic, in-process, NO LLM / API calls.
"""
import pytest

from knowledge_bank.agent_home import consult_for_agent

_AGENT = "mech-ledger"
_HOME  = "finance_royalties"


def _consult(query: str, max_domains: int = 4) -> dict:
    return consult_for_agent(_AGENT, query, max_domains=max_domains)


# ── Deep consult matrix (5 cross-domain scenarios) ───────────────────────────
#
# (query, expected_cross_domains)
# Invariant: "finance_royalties" leads; every expected cross-domain is present.
# Keywords commented per domain to document the routing logic.

DEEP_CONSULT_MATRIX = [
    (
        # finance_royalties: "mechanical", "royalt"
        # publishing: "co-write", "split sheet", "songwrit" (via "songwriter"),
        #             "catalog"
        "How do we verify that our MLC mechanical royalty collections match "
        "the co-write split sheet and confirm each songwriter is receiving "
        "the correct share from our streaming catalog?",
        ["publishing"],
    ),
    (
        # finance_royalties: "mechanical", "royalt"
        # legal: "contract", "clause", "negotiat" (via "negotiation")
        "The label is disputing our mechanical royalty income and we need to "
        "review the specific contract clause on mechanical rates — what "
        "contract terms and negotiation options should we examine?",
        ["legal"],
    ),
    (
        # finance_royalties: "mechanical", "royalt"
        # publishing: "publish" (via "publishing"), "catalog"
        # label_ops: "distribution deal", "royalty waterfall"
        "How do we track mechanical royalties earned from our full publishing "
        "catalog and align those collections with our label distribution deal "
        "royalty waterfall?",
        ["publishing", "label_ops"],
    ),
    (
        # finance_royalties: "mechanical", "royalt"
        # data_analytics: "forecast", "streaming data", "metric", "trajectory"
        "Can we forecast our annual mechanical royalty income by analyzing "
        "streaming data metrics and listener trajectory trends to project "
        "MLC collections?",
        ["data_analytics"],
    ),
    (
        # finance_royalties: "mechanical", "royalt"
        # sync: "sync", "licens" (via "licensing"), "tv", "advert", "placement"
        "We received a sync licensing offer for our song to appear in a TV "
        "advert — how do we collect the mechanical royalties generated by "
        "the sync placement?",
        ["sync"],
    ),
]

# ── Narrow / home-only scenario ───────────────────────────────────────────────
#
# A tightly-scoped CRB statutory rate question that returns ONLY
# "finance_royalties". Keywords triggered: "mechanical" (via "mechanical rate").
# Deliberately avoids: "publish" (publishing), "contract" / "clause" (legal),
# "sync" / "licens" (sync), "forecast" / "streaming data" (data_analytics),
# "distribution" (label_ops), "reconcil" (controller), "ern" (digital_ops).

_NARROW_QUERY = (
    "What is the statutory per-stream mechanical rate determined by the CRB "
    "and how do we track quarterly MLC disbursements for our recordings?"
)


# ── Tests ─────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize(
    "query, cross",
    DEEP_CONSULT_MATRIX,
    ids=[
        "mlc-collections-co-write-split-sheet-songwriter-catalog",
        "label-dispute-mechanical-contract-clause-negotiation",
        "publishing-catalog-distribution-deal-royalty-waterfall",
        "streaming-data-metrics-income-forecast-trajectory",
        "sync-tv-advert-mechanical-royalty-placement-collection",
    ],
)
def test_mech_ledger_consult_home_leads_and_cross_domains_present(query, cross):
    """
    mech-ledger's home domain 'finance_royalties' is always first; every
    expected cross-domain is present. Verifies home-first invariant and
    mechanical-royalty-specific cross-domain routing quality.
    """
    result = _consult(query)

    assert result["home_domain"] == _HOME, (
        f"expected home={_HOME!r}, got {result['home_domain']!r}"
    )
    assert result["domains"], "domains list is empty"
    assert result["domains"][0] == _HOME, (
        f"home domain must be first; got {result['domains']}"
    )
    for d in cross:
        assert d in result["domains"], (
            f"expected cross-domain {d!r} not found in {result['domains']}\n"
            f"Query: {query!r}"
        )
    assert result["knowledge"].strip(), "knowledge text is empty"


def test_mech_ledger_narrow_query_returns_home_domain_only():
    """
    A narrowly-scoped CRB statutory rate question (only 'mechanical' triggers)
    must return only the home domain 'finance_royalties' — no spurious
    cross-domain routing from publishing/legal/sync/analytics/label_ops terms.
    """
    result = _consult(_NARROW_QUERY)

    assert result["home_domain"] == _HOME
    assert result["domains"] == [_HOME], (
        f"expected ['{_HOME}'] only, got {result['domains']!r}\n"
        f"Query: {_NARROW_QUERY!r}"
    )
    assert result["knowledge"].strip(), "knowledge text is empty for narrow query"
